### ISSUE TITLE
Bild wird schwarz nachdem ein Button gedrückt wurde

### ISSUE THREAD

**Issue by oli1204** [sebmueller/Photobooth#10]
Hallo,

ich habe die Photobooth mehr oder weniger erfolgreich zum laufen gebracht.
Nach einigen Hürden habe ich es geschafft dass Photobooth endlich auf meinem Raspberry läuft. Leider noch nicht Fehlerfrei
Nachdem Photobooth gestartet wurde wird das Bild der Kamera angezeigt und im unteren Bereich zwei Layouts (vielleicht ist das schon der Fehler)
Nach dem drücken einer der beiden Buttons zählt der Countdown, nach der null wird das Bild schwarz und bleibt auch schwarz, wenn ich einen der Buttons drücke wird noch der Schriftzug "Fotobox" angezeigt, mehr tut sich aber nicht mehr.
Wo könnte der Fehler liegen? Die boot-config habe ich angepasst, leider ohne Erfolg.

noch eine Frage: wie kann ich das Programm photobooth beenden, so dass ich wieder normal auf meinen Raspberry zugreifen kann.

Vielen Dank für eure Hilfe

Gruß
Oliver

**Comment by oli1204** [comment]
vielleicht hilft das jemanden weiter:

AttributeError: 'Photobooth' object has no attribute 'overlay_last_photo'

**Comment by oli1204** [comment]
Ich habe selbst die Lösung gefunden, für alle die die Photobooth nachbauen wollen:
Bei mir hat es geholfen in der raspi-config im Menü "Memory-Split" den Wert auf 256 zu ändern.
Danach lief das Skript ohne Probleme

**Comment by sebmueller** [comment]
Hallo,

ich habe es leider erst jetzt gesehen, dass hier ein Eintrag war.
Die Bilder im Speicher benötigen viel Platz. Memorysplit sollte auf 256 oder mehr gestellt werden. Bei höheren Auflösungen ist noch mehr Speicher notwendig.
