### ISSUE TITLE
Problem beim Testen von photobooth.py

### ISSUE THREAD

**Issue by whiteman-michel** [sebmueller/Photobooth#2]
Hallo.
Erst mal Kompliment für die super Beschreibung und den sehr interessanten Artikel im Heft.

Ich bin gerade dabei Ihre Idee umzusetzen. Die Installation hat gut geklappt... beim dem Testen der Software erhalte ich nun diese Meldung:
![fehler4 (2)](https://user-images.githubusercontent.com/55814160/65838006-86a45d00-e2fe-11e9-9d01-6f7e2c34ad91.png)

mmal: mmal_vc_shm_init: could not initialize vc shared memory service
mmal: mmal_vc_component_create: failed to initialise shm for 'vc.camera_info' (7                                                                                                             :EIO)
mmal: mmal_component_create_core: could not create component 'vc.camera_info' (7                                                                                                             )

Mit diesen Angaben kann ich leider nichts anfangen. Hart das etwas mit den Rechten zu tun?
Vielen Dank für Ihre Rückantwort.
MfG
Michael Bauer

**Comment by chgaertner** [comment]
Hallo Michel,

ohne das auf die Schnelle im Detail überprüfen zu können, einige Gedanken:
- ist die Kamera in raspi-config aktiviert?
- hast Du anschließend neu gestartet?
- ist die Kamera richtig angeschlossen (blaue Markierung am Kabel Richtung Netzwerkbuchse)?
- kannst Du mit "raspistill -o test.jpg" ein Foto machen?

LG Christian
