### ISSUE TITLE
Problem (und Lösung), wenn der Raspberry Pi von einem USB-Stick bootet

### ISSUE THREAD

**Issue by chgaertner** [sebmueller/Photobooth#3]
Liebe Alle,

das Programm sucht automatisch nach einem USB-Stick, um dort die Fotos ablegen zu können. Wenn der Raspberry Pi von einem USB-Stick bootet (statt der MicroSD-Karte), dann findet das Programm stets "/boot" als Mountpoint des USB-Sticks und kann dort natürlich kein Verzeichnis für die Fotos erstellen und daher keine Fotos anlegen.

Die "quick-and-dirty"-Lösung schaut so aus:
- Verzeichnis DATEN unterhalb von Photobooth anlegen
- Datei photobooth.py bearbeiten:
-- nach Zeile 1149 ("def GetMountpoint(self):") einfügen
-- return "/home/pi/Photobooth/DATEN/"
-- Achtung auf die richtige Einrückung mit Leerzeichen, muß wie die folgende Zeile (logging...) sein!

In diesem Fall kann man sich das ganze Automount-Thema auch gleich sparen, weil der USB-Stick ja eh schon gemountet ist.

LG Christian

**Comment by sebmueller** [comment]
Danke für den Hinweis mit dem USB Stick. Davon zu Booten habe ich noch nicht probiert. Das mit dem Automount ist natürlich ein Argument.
