### ISSUE TITLE
Problem mit den Tasten

### ISSUE THREAD

**Issue by chgaertner** [sebmueller/Photobooth#4]
Liebe Alle,

ich habe - wie in der Bauanleitung vorgeschlagen - zwei Taster an die entsprechenden Ports des Raspberry Pi angeschlossen. Nun ist mir folgendes Problem aufgefallen: wenn man denselben Taster drückt, der beim letzten Schritt gedrückt wurde, funktioniert er erst gefühlte 2 bis 3 Sekunden nachdem die entsprechende Beschriftung am Bildschirm erscheint. Wenn man den anderen Taster nimmt, funktioniert er unmittelbar nach dem Erscheinen der Beschriftung.

Beispiel 1:
- Start
- Layout 2 wird ausgewählt (=Taster 2 rechts)
- Foto wird gemacht, man möchte es nochmals machen (= Taster 1 links)
- in diesem Fall funktioniert der Taster unmittelbar nachdem die Beschriftung erscheint

Beispiel 2:
- Start
- Layout 2 wird ausgewählt (=Taster 2 rechts)
- Foto wird gemacht, man möchte weiter zum nächsten Foto (= Taster 2 rechts)
- in diesem Fall funktioniert der Taster erst nach 2 bis 3 Sekunden

In der Log-Datei erscheinen nach der Aufnahme folgende Zeilen **bevor** ein Taster gedrückt wurde:
core-enter:141 - Entered state ShowPhoto
core-enter:141 - Entered state TakePhoto
core-enter:141 - Entered state CountdownPhoto
photobooth-Button2pressed:618 - **self.button2 ready -> Set new TimeStamp**
photobooth-Button2pressed:565 - **Button2pressed**

Und zwar erscheinen immer **vor** dem Drücken eines Tasters diese letzten beiden Zeilen für genau jenen Taster, die man bei der letzten Auswahl gedrückt hatte. Wenn man zuvor also Taster 1 gedrückt hatte, erscheinen in der Log-Datei diese Zeilen **bevor** ein Taster gedrückt wurde:
core-enter:141 - Entered state ShowPhoto
core-enter:141 - Entered state TakePhoto
core-enter:141 - Entered state CountdownPhoto
photobooth-Button2pressed:618 - **self.button1 ready -> Set new TimeStamp**
photobooth-Button2pressed:565 - **Button1pressed**

Leider sind meine Python-Kenntnisse nicht so fundiert, daß ich da jetzt draufkommen würde, woher das Programm diesen ersten Tastendruck hat. :-(

Hat jemand von euch eine Idee dazu?

Danke!

LG Christian

**Comment by chgaertner** [comment]
So, auf einen Workaround bin ich auch schon gekommen:

**Zeilen 300 und 301:**
- GPIO.RISING statt GPIO.FALLING

**Button1pressed(self, event):**
- Block mit "if self.button1active:" auskommentieren
- Block mir "# wait until button is released" auskommentieren

**Button2pressed(self, event):**
- Block mit "if self.button2active:" auskommentieren
- Block mir "# wait until button is released" auskommentieren

Damit reagieren die Taster nun nahezu verzögerungsfrei auf das Drücken, egal ob es der selbe wie beim letzten Schritt ist oder nicht.

Glücklich bin ich mit der Lösung allerdings nicht, denn es behebt ja nicht die eigentliche Ursache ...

LG Christian

**Comment by sebmueller** [comment]
Das Problem scheint am Prellen der Taster zu liegen.  
Das Verzögern soll das Prellen beheben.
