### ISSUE TITLE
problem with versions CUPS + Gutenprint

### ISSUE THREAD

**Issue by MWestermeier** [sebmueller/Photobooth#5]
There is a version conflict with gutenprint and cups on the Canon Selphy 1300 printer within the newest Raspbian "Buster". When using the photobooth.py it does not print, also a try with "lp test.jpg" fails on the printer

The CUPS-log says:
> The PPD version (5.3.3) is not compatible with Gutenprint 5.3.1. Please run `/usr/sbin/cups-genppdupdate' as administrator. 

I tried to do the announced update but it did not help.
I recognized, that the failure message above states incompatibility with gutenprint version 5.3.1 but the installed gutenprint version is clearly 5.3.3

**Comment by MWestermeier** [comment]
It seems that I have found a workaround to solve this issue:

1. Copy the file /etc/cups/ppd/Canon_CP1300.ppd to USB-stick
2. Open the file Canon_CP1300.ppd on PC and change manually the lines
        *FileVersion:	"5.3.3"   =>   *FileVersion:	"5.3.1"
        *NickName:      "Canon SELPHY CP1300 - CUPS+Gutenprint v5.3.3"   =>   *NickName:      "Canon SELPHY CP1300 - CUPS+Gutenprint v5.3.1"
3. Go to CUPS webportal on PC and choose "change printer" on the printer settings of CP1300
4. When asked for driver, choose the one you manually changed PPD from your PC
5. Check afterwards that Printer is named ".... CUPS+Gutenprint v5.3.1"
6. Reboot RasPi and try printing again :-)

**Comment by sebmueller** [comment]
Thank you for this hint!
