### ISSUE TITLE
Bildschirm wird nach 3 Sekunden aus.

### ISSUE THREAD

**Issue by Monaco85** [sebmueller/Photobooth#6]
Vielen Dank für die Anleitung. Ich habe sie Schritt für Schritt durchgeführt. Wenn ich das Photobooth.py starte sehe ich am Bildschirm meine Kamera für ca. 3 Sekunden. Danach wird das Bild schwarz, die Kamera bleibt an. Dieser Zustand ändert sich nichtmehr. Der letzte Logeintrag ist "Entered state Start".

**Comment by skar-cgn** [comment]
Hallo, 
das Problem hatte ich auch. 
Bei mir hat geholfen die Einstellungen wie hier beschrieben in der Boot.ini vorzunehmen. 
https://github.com/sebmueller/Photobooth#change-resolution-if-necessary

**Comment by oli1204** [comment]
Bei mir hat es geholfen in der raspi-config im Menü "Memory-Split" den Wert auf 256 zu ändern.
Danach lief das Skript ohne Probleme
