### ISSUE TITLE
Bildschirmauflösung ungleich 1024x600

### ISSUE THREAD

**Issue by Monaco85** [sebmueller/Photobooth#7]
Ich habe das Projekt mit einem 4/3 Monitor realiert. leider fliegt mir der Programm jedes mal nachdem das erte Photo gemacht wurde ab. Hat jemand eine Idee

**Comment by oli1204** [comment]
Hallo Monaco85,

ich habe vermutlich das gleiche Problem, hast du hier schon eine Lösung gefunden?

**Comment by oli1204** [comment]
Bei mir hat es geholfen in der raspi-config im Menü "Memory-Split" den Wert auf 256 zu ändern.
Danach lief das Skript ohne Probleme
